

services:
  myDB:
    image: postgres:16
    container_name: pluma-de-cuervo-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresPluma
      - POSTGRES_PASSWORD=postgresPluma
      - POSTGRES_DB=pluma-de-cuervo-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
